### ISSUE TITLE
"Add Missing Version(s)" does nothing

### ISSUE THREAD

**Issue by marianrh** [jfrog/gocenter#52]
Hi,
I'm looking at https://search.gocenter.io/github.com/mattn/go-sqlite3?tab=versions. Under "Missing Versions", the version v1.14.1 is currently listed. I need this version and want to add it. However, clicking the button "Add Missing Version(s)" has no effect other than showing a click animation.

Thanks, Marian

**Comment by marianrh** [comment]
v1.14.1 is now shown under "Processed Versions".

**Comment by elioengcomp** [comment]
Hi @marianrh ,

Thanks for your message. I'm glad you found the module you were looking for.

I just want to point out that you don't need to use the UI or wait for a module to be visible there in order to fetch it from GoCenter. If you have your GOPROXY set pointing to GoCenter you can just run a `go get <PATH>@<VERSION>` and that will cause GoCenter to fetch and serve the missing version on demand.
